name: Swift

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        xcversion list
        xcversion select 11.1
        xcodebuild -version
        swift --version
        swift build -v
    - name: Run tests
      run: swift test -v
