name: Test Packages

on:
  push:
    branches:    
      - main

jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1
    - name: Prepare Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_11.4.app
        xcodebuild -version
        swift --version
    - name: Boot simulator
      run: xcrun simctl boot "iPhone 11 Pro"
    - name: Build for testing
      run: xcodebuild build-for-testing -workspace .swiftpm/xcode/package.xcworkspace -scheme Support-Package -destination "name=iPhone 11 Pro"
    - name: Run tests
      run: xcodebuild test-without-building -workspace .swiftpm/xcode/package.xcworkspace -scheme Support-Package -destination "name=iPhone 11 Pro"
